import { readFile, writeFile } from "node:fs/promises";
import { join as joinPaths } from "node:path";
import type { AsyncFunctionArguments } from "@actions/github-script";
import type { PaginateInterface } from "@octokit/plugin-paginate-rest";
import type { Api } from "@octokit/plugin-rest-endpoint-methods";
import { fromURL as loadSVGFromURL } from "cheerio";

const PROJECT_ROOT = joinPaths(import.meta.dirname, "..", "..");

type ScriptFunctionArgs = AsyncFunctionArguments & {
	github: Api & {
		paginate: PaginateInterface;
	};
	workspace: string;
};

/**
 * Returns num with suffix k(thousands)/M(millions), precise to one decimal place.
 * @param num The number to format.
 * @returns The formatted number.
 */
function formatNumber(num: number): string {
	const abs = Math.abs(num);
	const sign = Math.sign(num);

	if (abs < 1_000) {
		return `${sign * abs}`;
	}
	if (abs < 1_000_000) {
		return `${sign * parseFloat((abs / 1_000).toFixed(1))}k`;
	}
	return `${sign * parseFloat((abs / 1_000_000).toFixed(1))}M`;
}

/**
 * Returns public organization memberships of a user as negated search query
 * qualifiers.
 * @param github Octokit GitHub client instance.
 * @param username Name of the user to lookup.
 */
async function getNotOrgQualifiers(
	github: ScriptFunctionArgs["github"],
	username: string,
): Promise<string> {
	const { data } = await github.rest.orgs.listForUser({ username });
	return data.map((org) => `-org:${org.login}`).join(" ");
}

/**
 * Returns the count of contributions to open-source community projects,
 * both completed issues and merged pull requests.
 * @param github Octokit GitHub client instance.
 * @param byAuthor Which author/user to get the count for.
 */
async function getTotalContributions(
	github: ScriptFunctionArgs["github"],
	byAuthor: string,
): Promise<string> {
	let notOrgQualifiers = await getNotOrgQualifiers(github, byAuthor);
	// Prepend a space separator if any qualifiers were returned.
	if (notOrgQualifiers) notOrgQualifiers = ` ${notOrgQualifiers}`;

	// These return only public data (as it should for OPEN-source contributions)
	// as long as the GitHub client token doesn't have private organization read
	// permissions.
	const [
		{
			data: { total_count: issuesCount },
		},
		{
			data: { total_count: pullRequestsCount },
		},
	] = await Promise.all([
		github.rest.search.issuesAndPullRequests({
			q: `is:issue reason:completed author:${byAuthor} -user:${byAuthor}${notOrgQualifiers}`,
			per_page: 1, // We're only interested in the total count.
		}),
		github.rest.search.issuesAndPullRequests({
			q: `is:pr is:merged author:${byAuthor} -user:${byAuthor}${notOrgQualifiers}`,
			per_page: 1, // We're only interested in the total count.
		}),
	]);

	return formatNumber(pullRequestsCount + issuesCount);
}

/**
 * Fetches the SVG stats card generated by the GitHub Stats Extended project,
 * and extracts the total stars earned and commits authored from it.
 * @param username Which author/user to get the stats for.
 */
async function getTotalStarsEarnedAndCommitsAuthored(
	username: string,
): Promise<{
	totalStarsEarned: string;
	totalCommitsAuthored: string;
}> {
	const svgURL = new URL(
		"https://github-stats-extended.vercel.app/api?hide_rank=true&hide_title=true&include_all_commits=true&disable_animations=true&cache_seconds=86400",
	);
	svgURL.searchParams.set("username", username);

	const svg$ = await loadSVGFromURL(svgURL);
	return {
		// Fortunately GSE has special data attributes on the exact elements I need!
		totalStarsEarned: svg$("[data-testid='stars']").text().trim(),
		totalCommitsAuthored: svg$("[data-testid='commits']").text().trim(),
	};
}

/**
 * Fetches the npm downloads per year badge generated by shields.io,
 * and extracts the value from it.
 * @param author Which npm author/user to get the stats for.
 */
async function getNPMDownloadsPerYear(author: string) {
	const svgURL = new URL(
		"https://img.shields.io/npm-stat/dy/?style=social&label=&cacheSeconds=15768000",
	);
	svgURL.pathname += author;

	const svg$ = await loadSVGFromURL(svgURL);
	// The "social" style badge has a unique id attribute on the exact element I need!
	const downloadsPerYearStr = svg$("#rlink").text().trim();
	if (downloadsPerYearStr.toLowerCase().endsWith("/year")) {
		return downloadsPerYearStr.slice(0, -"/year".length);
	}
	return downloadsPerYearStr;
}

/**
 * Fetches the SVG top languages card generated by the GitHub Stats Extended
 * project, and extracts the top languages from it.
 * @param username Which author/user to get the top languages for.
 */
async function getTopLanguages(username: string): Promise<[string, string][]> {
	const svgURL = new URL(
		"https://github-stats-extended.vercel.app/api/top-langs?hide_title=true&langs_count=8&disable_animations=true&size_weight=0.5&count_weight=0.5&cache_seconds=86400",
	);
	svgURL.searchParams.set("username", username);
	svgURL.searchParams.set("hide", "PHP"); // My PHP days are pretty much over...

	const svg$ = await loadSVGFromURL(svgURL);
	const topLanguages: [string, string][] = [];
	let javaScriptIndex = -1;
	let typeScriptIndex = -1;
	for (const langEl of svg$("[data-testid='lang-name']")) {
		let valueEl = langEl.nextSibling;
		while (valueEl?.type !== "tag") {
			valueEl = valueEl ? valueEl.nextSibling : null;
		}
		if (valueEl?.name !== "text") {
			throw new Error("Failed to find language percentage element");
		}

		const lang = svg$(langEl).text().trim();
		const newLen = topLanguages.push([lang, svg$(valueEl).text().trim()]);

		// If the current language is JavaScript or TypeScript, record for later.
		const langNorm = lang.toLowerCase();
		if (langNorm === "javascript") {
			javaScriptIndex = newLen - 1;
		} else if (langNorm === "typescript") {
			typeScriptIndex = newLen - 1;
		}
	}

	// Merge JavaScript and TypeScript into one entry.
	if (
		javaScriptIndex !== -1 &&
		typeScriptIndex !== -1 &&
		topLanguages[javaScriptIndex] &&
		topLanguages[typeScriptIndex]
	) {
		const [tsLang, tsValue] = topLanguages[typeScriptIndex]!;
		const [jsLang, jsValue] = topLanguages[javaScriptIndex]!;
		const jsTsValue = Number.parseFloat(jsValue) + Number.parseFloat(tsValue);
		if (Number.isNaN(jsTsValue)) {
			throw new Error(
				`Invalid JS/TS values extracted from top languages SVG: ${jsValue}/${tsValue}`,
			);
		}
		topLanguages[javaScriptIndex] = [
			`${jsLang}/${tsLang}`,
			`${jsTsValue.toFixed(2)}%`,
		];
		topLanguages.splice(typeScriptIndex, 1);
	}

	// Sort top languages again after potentially merging JS and TS.
	topLanguages.sort(([, a], [, b]) => {
		const aNum = Number.parseFloat(a);
		if (Number.isNaN(aNum)) {
			throw new Error(`Invalid value in extracted top languages: ${a}`);
		}
		const bNum = Number.parseFloat(b);
		if (Number.isNaN(bNum)) {
			throw new Error(`Invalid value in extracted top languages: ${b}`);
		}
		return bNum - aNum;
	});

	return topLanguages;
}

export default async ({ github, context }: ScriptFunctionArgs) => {
	// TODO: Fetch data for top languages and display it.

	const owner = context.repo.owner;
	const [
		npmDownloadsPerYear,
		{ totalStarsEarned, totalCommitsAuthored },
		totalContributions,
		topLanguages,
	] = await Promise.all([
		getNPMDownloadsPerYear(owner),
		getTotalStarsEarnedAndCommitsAuthored(owner),
		getTotalContributions(github, owner),
		getTopLanguages(owner),
	]);

	let topLanguagesValueMaxLength = 0;
	for (const [, value] of topLanguages) {
		const len = value.length;
		if (len > topLanguagesValueMaxLength) {
			topLanguagesValueMaxLength = len;
		}
	}
	const padding = Math.max(
		6, // Default for many manpages.
		npmDownloadsPerYear.length,
		totalStarsEarned.length,
		totalCommitsAuthored.length,
		totalContributions.length,
		topLanguagesValueMaxLength,
	);

	const statisticsStr = `     ${npmDownloadsPerYear.padEnd(padding)} npm downloads per year ↓

     ${totalStarsEarned.padEnd(padding)} total stars earned ★

     ${totalCommitsAuthored.padEnd(padding)} total commits authored ⏲

     ${totalContributions.padEnd(padding)} total contributions to open-source community projects 🕮`;

	const topLanguagesStr: string[] = [];
	for (const [lang, value] of topLanguages) {
		topLanguagesStr.push(`     ${value.padEnd(padding)} ${lang}`);
	}

	let readme = await readFile(
		joinPaths(PROJECT_ROOT, "README.md.tmpl"),
		"utf8",
	);
	readme = readme.replace("{{statistics}}", statisticsStr);
	readme = readme.replace("{{topLanguages}}", topLanguagesStr.join("\n\n"));
	await writeFile(joinPaths(PROJECT_ROOT, "README.md"), readme);
};
