import { readFile, writeFile } from "node:fs/promises";
import { join as joinPaths } from "node:path";
import type { AsyncFunctionArguments } from "@actions/github-script";
import type { PaginateInterface } from "@octokit/plugin-paginate-rest";
import type { Api } from "@octokit/plugin-rest-endpoint-methods";
import { fromURL as loadSVGFromURL } from "cheerio";

const PROJECT_ROOT = joinPaths(import.meta.dirname, "..", "..");

type ScriptFunctionArgs = AsyncFunctionArguments & {
	github: Api & {
		paginate: PaginateInterface;
	};
	workspace: string;
};

/**
 * Returns num with suffix k(thousands)/M(millions), precise to one decimal place.
 * @param num The number to format.
 * @returns The formatted number.
 */
function formatNumber(num: number): string {
	const abs = Math.abs(num);
	const sign = Math.sign(num);

	if (abs < 1_000) {
		return `${sign * abs}`;
	}
	if (abs < 1_000_000) {
		return `${sign * parseFloat((abs / 1_000).toFixed(1))}k`;
	}
	return `${sign * parseFloat((abs / 1_000_000).toFixed(1))}M`;
}

/**
 * Returns public organization memberships of a user as negated search query
 * qualifiers.
 * @param github Octokit GitHub client instance.
 * @param username Name of the user to lookup.
 */
async function getNotOrgQualifiers(
	github: ScriptFunctionArgs["github"],
	username: string,
): Promise<string> {
	const { data } = await github.rest.orgs.listForUser({ username });
	return data.map((org) => `-org:${org.login}`).join(" ");
}

/**
 * Returns the count of contributions to open-source community projects,
 * both completed issues and merged pull requests.
 * @param github Octokit GitHub client instance.
 * @param byAuthor Which author/user to get the count for.
 */
async function getTotalContributions(
	github: ScriptFunctionArgs["github"],
	byAuthor: string,
): Promise<string> {
	let notOrgQualifiers = await getNotOrgQualifiers(github, byAuthor);
	// Prepend a space separator if any qualifiers were returned.
	if (notOrgQualifiers) notOrgQualifiers = ` ${notOrgQualifiers}`;

	// These return only public data (as it should for OPEN-source contributions)
	// as long as the GitHub client token doesn't have private organization read
	// permissions.
	const [
		{
			data: { total_count: issuesCount },
		},
		{
			data: { total_count: pullRequestsCount },
		},
	] = await Promise.all([
		github.rest.search.issuesAndPullRequests({
			q: `is:issue reason:completed author:${byAuthor} -user:${byAuthor}${notOrgQualifiers}`,
			per_page: 1, // We're only interested in the total count.
		}),
		github.rest.search.issuesAndPullRequests({
			q: `is:pr is:merged author:${byAuthor} -user:${byAuthor}${notOrgQualifiers}`,
			per_page: 1, // We're only interested in the total count.
		}),
	]);

	return formatNumber(pullRequestsCount + issuesCount);
}

/**
 * Fetches the SVG stats card generated by the GitHub Stats Extended project,
 * and extracts the total stars earned and commits authored from it.
 * @param username Which author/user to get the stats for.
 */
async function getTotalStarsEarnedAndCommitsAuthored(
	username: string,
): Promise<{
	totalStarsEarned: string;
	totalCommitsAuthored: string;
}> {
	const svgURL = new URL(
		"https://github-stats-extended.vercel.app/api?hide_rank=true&hide_title=true&include_all_commits=true&disable_animations=true&cache_seconds=86400",
	);
	svgURL.searchParams.set("username", username);

	const svg$ = await loadSVGFromURL(svgURL);
	return {
		// Fortunately GSE has special data attributes on the exact elements I need!
		totalStarsEarned: svg$("[data-testid='stars']").text(),
		totalCommitsAuthored: svg$("[data-testid='commits']").text(),
	};
}

/**
 * Fetches the npm downloads per year badge generated by shields.io,
 * and extracts the value from it.
 * @param author Which npm author/user to get the stats for.
 */
async function getNPMDownloadsPerYear(author: string) {
	const svgURL = new URL(
		"https://img.shields.io/npm-stat/dy/?style=social&label=&cacheSeconds=15768000",
	);
	svgURL.pathname += author;

	const svg$ = await loadSVGFromURL(svgURL);
	// The "social" style badge has a unique id attribute on the exact element I need!
	const downloadsPerYearStr = svg$("#rlink").text().trim();
	if (downloadsPerYearStr.toLowerCase().endsWith("/year")) {
		return downloadsPerYearStr.slice(0, -"/year".length);
	}
	return downloadsPerYearStr;
}

export default async ({ github, context }: ScriptFunctionArgs) => {
	// TODO: Fetch data for top languages and display it.

	const owner = context.repo.owner;
	const [
		npmDownloadsPerYear,
		{ totalStarsEarned, totalCommitsAuthored },
		totalContributions,
	] = await Promise.all([
		getNPMDownloadsPerYear(owner),
		getTotalStarsEarnedAndCommitsAuthored(owner),
		getTotalContributions(github, owner),
	]);

	const statisticsPadEnd = Math.max(
		6, // Default for many manpages.
		npmDownloadsPerYear.length,
		totalStarsEarned.length,
		totalCommitsAuthored.length,
		totalContributions.length,
	);
	const statistics = `     ${npmDownloadsPerYear.padEnd(statisticsPadEnd)} npm downloads per year

     ${totalStarsEarned.padEnd(statisticsPadEnd)} total stars earned

     ${totalCommitsAuthored.padEnd(statisticsPadEnd)} total commits authored

     ${totalContributions.padEnd(statisticsPadEnd)} total contributions to open-source community projects`;

	let readme = await readFile(
		joinPaths(PROJECT_ROOT, "README.md.tmpl"),
		"utf8",
	);
	readme = readme.replace("{{statistics}}", statistics);
	await writeFile(joinPaths(PROJECT_ROOT, "README.md"), readme);
};
