name: Update README

on:
  schedule:
    - cron: 0 4 * * 1 # At 04:00 on Monday.

  push:
    branches:
      - main
    paths:
      - README.md.tmpl

  workflow_dispatch:

jobs:
  update-readme:
    name: Update README

    concurrency:
      group: update-readme
      cancel-in-progress: false

    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: true # We need those later.

      - name: Set up pnpm & Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          working-directory: &working-directory .github/scripts
          cache: true
          require-lockfile: true
          install: false

      - name: Install dependencies
        working-directory: *working-directory
        run: pnpm install --prod

      - name: Update README
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          # language=javascript
          script: |
            const workspace = "${{ github.workspace }}";
            const { default: script } = await import(workspace + "/.github/scripts/update-readme.ts")
            await script({ context, core, github, octokit, getOctokit, exec, glob, io, require, __original_require__, workspace });

      - name: Commit & push potential changes
        # language="shell script"
        run: |
          # Check dirty state of repo using git-status.
          gitStatus="$(git status -s .)"
          if [[ -n "${gitStatus}" ]]; then
              # Add files.
              git add .

              # Check dirty state of repo again using git-diff.
              gitStatus="$(git diff --staged)"
              if [[ -n "${gitStatus}" ]]; then
                  # Create a new commit.
                  date="$(date -I)"
                  git \
                      -c user.name="github-actions[bot]" \
                      -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
                      commit -m "chore: readme update ${date}"

                  # Push new commit.
                  git push origin
              else
                  echo "Working tree clean. Nothing to commit.";
              fi
          else
            echo "Working tree clean. Nothing to commit.";
          fi
